import React, { createContext, useCallback, useContext, useMemo, useState } from "react";
import type { Language } from "@/lib/types";

type TranslationRecord = Record<Language, string>;

const translations: Record<string, TranslationRecord> = {
  "nav.home": { ru: "Главная", en: "Home", ro: "Acasă" },
  "nav.tagline": { ru: "под ключ", en: "turnkey", ro: "la cheie" },
  "nav.calc": { ru: "Калькулятор", en: "Estimate", ro: "Calculator" },
  "nav.dashboard": { ru: "Кабинет", en: "Dashboard", ro: "Panou" },
  "nav.pro": { ru: "PRO", en: "PRO", ro: "PRO" },
  "nav.admin": { ru: "Админ", en: "Admin", ro: "Admin" },
  "nav.signin": { ru: "Войти", en: "Sign in", ro: "Autentificare" },
  "nav.signout": { ru: "Выйти", en: "Sign out", ro: "Ieșire" },
  "nav.role": { ru: "Роль", en: "Role", ro: "Rol" },
  "role.guest": { ru: "Гость", en: "Guest", ro: "Vizitator" },
  "role.user": { ru: "Пользователь", en: "User", ro: "Utilizator" },
  "role.pro": { ru: "PRO", en: "PRO", ro: "PRO" },
  "role.admin": { ru: "Админ", en: "Admin", ro: "Admin" },
  "theme.label": { ru: "Тема", en: "Theme", ro: "Temă" },
  "theme.light": { ru: "Светлая", en: "Light", ro: "Deschisă" },
  "theme.dark": { ru: "Тёмная", en: "Dark", ro: "Întunecată" },
  "theme.system": { ru: "Системная", en: "System", ro: "Sistem" },
  "language.label": { ru: "Язык", en: "Language", ro: "Limba" },
  "currency.label": { ru: "Валюта", en: "Currency", ro: "Monedă" },
  "cta.calculate": { ru: "Рассчитать смету", en: "Calculate estimate", ro: "Calculează deviz" },
  "cta.start": { ru: "Начать за 2 минуты", en: "Start in 2 minutes", ro: "Pornește în 2 minute" },
  "cta.download": { ru: "Скачать PDF", en: "Download PDF", ro: "Descarcă PDF" },
  "cta.save": { ru: "Сохранить", en: "Save", ro: "Salvează" },
  "cta.share": { ru: "Поделиться", en: "Share", ro: "Distribuie" },
  "cta.preview": { ru: "Предпросмотр", en: "Preview", ro: "Previzualizare" },
  "cta.update": { ru: "Обновить", en: "Update", ro: "Actualizează" },
  "cta.add": { ru: "Добавить", en: "Add", ro: "Adaugă" },
  "cta.generate": { ru: "Сформировать смету", en: "Generate estimate", ro: "Generează deviz" },
  "cta.edit": { ru: "Редактировать", en: "Edit", ro: "Editează" },
  "cta.duplicate": { ru: "Дублировать", en: "Duplicate", ro: "Duplica" },
  "cta.delete": { ru: "Удалить", en: "Delete", ro: "Șterge" },
  "cta.exportCsv": { ru: "Экспорт CSV", en: "Export CSV", ro: "Export CSV" },
  "cta.aiAssistant": { ru: "AI помощник", en: "AI Assistant", ro: "Asistent AI" },
  "cta.generateDraft": { ru: "Generate Draft", en: "Generate Draft", ro: "Generează schiță" },
  "cta.improveLayout": { ru: "Improve Layout", en: "Improve Layout", ro: "Îmbunătățește layout" },
  "cta.addVariant": { ru: "Add Variant", en: "Add Variant", ro: "Adaugă variantă" },
  "cta.autoBind": { ru: "Auto-bind", en: "Auto-bind", ro: "Auto-bind" },
  "cta.previewEstimate": { ru: "Preview with estimate", en: "Preview with estimate", ro: "Previzualizează cu deviz" },
  "cta.exportSvg": { ru: "Export SVG", en: "Export SVG", ro: "Export SVG" },
  "cta.send": { ru: "Отправить", en: "Send", ro: "Trimite" },
  "hero.title": {
    ru: "RenovEstimate — смета ремонта и инженерии “под ключ” за 2–5 минут",
    en: "RenovEstimate — turnkey renovation estimate in 2–5 minutes",
    ro: "RenovEstimate — deviz complet în 2–5 minute",
  },
  "hero.subtitle": {
    ru: "3 пакета, прозрачная методика расчёта, детальные работы и материалы с аналогами, готовый PDF.",
    en: "3 packages, transparent math, detailed works & materials with analogs, ready PDF.",
    ro: "3 pachete, calc transparent, lucrări & materiale detaliate cu analogi, PDF gata.",
  },
  "hero.badge": {
    ru: "Смета + схемы по шаблонам",
    en: "Estimate + template-based diagrams",
    ro: "Deviz + scheme pe șabloane",
  },
  "how.title": { ru: "Как это работает", en: "How it works", ro: "Cum funcționează" },
  "how.step1": {
    ru: "Заполните параметры объекта и инженерных систем.",
    en: "Fill in the property and engineering systems parameters.",
    ro: "Completează parametrii obiectului și ai sistemelor.",
  },
  "how.step2": {
    ru: "Получите 3 пакета с диапазоном цены и сроками.",
    en: "Get 3 packages with price range and timelines.",
    ro: "Primești 3 pachete cu interval de preț și termene.",
  },
  "how.step3": {
    ru: "Скачайте PDF со схемами, этапами и чек-листом ошибок.",
    en: "Download PDF with diagrams, stages, and error checklist.",
    ro: "Descarcă PDF cu scheme, etape și checklist.",
  },
  "demo.title": { ru: "Примеры (демо)", en: "Examples (demo)", ro: "Exemple (demo)" },
  "faq.title": { ru: "FAQ", en: "FAQ", ro: "Întrebări" },
  "faq.q1": { ru: "Сколько времени занимает расчёт?", en: "How long does the estimate take?", ro: "Cât durează calculul?" },
  "faq.a1": { ru: "2–5 минут на ввод параметров и мгновенная генерация пакетов.", en: "2–5 minutes to input data and instant package generation.", ro: "2–5 minute pentru completare și generare instantă." },
  "faq.q2": { ru: "Можно ли сохранить смету?", en: "Can I save the estimate?", ro: "Pot salva devizul?" },
  "faq.a2": { ru: "Да, после входа смета сохраняется в вашем кабинете.", en: "Yes, after login it is saved to your dashboard.", ro: "Da, după autentificare se salvează în panou." },
  "faq.q3": { ru: "Откуда берутся коэффициенты?", en: "Where do coefficients come from?", ro: "De unde vin coeficienții?" },
  "faq.a3": { ru: "Из региональных правил и выбранной срочности/сложности.", en: "From regional rules and urgency/complexity.", ro: "Din reguli regionale și urgență/complexitate." },
  "faq.q4": { ru: "Схемы генерируются автоматически?", en: "Are diagrams auto-generated?", ro: "Schemele sunt generate automat?" },
  "faq.a4": { ru: "Нет, схемы создаются шаблонами и правилами в админке.", en: "No, diagrams are built from admin templates and rules.", ro: "Nu, schemele vin din șabloane și reguli." },
  "faq.q5": { ru: "Есть ли watermark в PDF?", en: "Is there a watermark in PDF?", ro: "Există watermark în PDF?" },
  "faq.a5": { ru: "Для гостя — DEMO, для PRO — без watermark и с брендингом.", en: "Guest PDFs have DEMO; PRO gets branding without watermark.", ro: "Guest: DEMO, PRO: fără watermark, cu branding." },
  "faq.q6": { ru: "Как обновляются курсы валют?", en: "How are FX rates updated?", ro: "Cum se actualizează cursul?" },
  "faq.a6": { ru: "Админ обновляет курсы, пересчёт происходит автоматически.", en: "Admin updates rates; recalculation is automatic.", ro: "Admin actualizează, recalcularea e automată." },
  "faq.q7": { ru: "Поддерживаются ли аналоги материалов?", en: "Are material analogs supported?", ro: "Sunt suportate materialele analog?" },
  "faq.a7": { ru: "Да, в каталоге хранится по два аналога.", en: "Yes, catalog stores two analogs.", ro: "Da, catalogul are doi analogi." },
  "faq.q8": { ru: "Можно ли настроить коэффициенты?", en: "Can I edit coefficients?", ro: "Pot edita coeficienții?" },
  "faq.a8": { ru: "Для PRO доступны настройки маржи и скидки.", en: "PRO can adjust margin and discount.", ro: "PRO poate ajusta marja și discountul." },
  "faq.q9": { ru: "Есть ли экспорт лидов?", en: "Is lead export available?", ro: "Există export lead-uri?" },
  "faq.a9": { ru: "Для PRO — экспорт CSV и share-link.", en: "PRO gets CSV export and share links.", ro: "PRO are export CSV și link share." },
  "faq.q10": { ru: "Могу ли я менять шаблоны схем?", en: "Can I edit diagram templates?", ro: "Pot edita șabloanele de scheme?" },
  "faq.a10": { ru: "Да, в админке есть конструктор схем и правила.", en: "Yes, admin has diagram builder and rules.", ro: "Da, în admin există constructor și reguli." },
  "faq.q11": { ru: "Поддерживаются ли несколько языков?", en: "Are multiple languages supported?", ro: "Se suportă mai multe limbi?" },
  "faq.a11": { ru: "Да, RU/EN/RO с сохранением выбора.", en: "Yes, RU/EN/RO with saved preference.", ro: "Da, RU/EN/RO cu preferințe salvate." },
  "faq.q12": { ru: "Есть ли история смет?", en: "Is there estimate history?", ro: "Există istoric devize?" },
  "faq.a12": { ru: "Да, в кабинете можно управлять сметами.", en: "Yes, manage estimates in the dashboard.", ro: "Da, gestionezi devizele în panou." },
  "pro.title": { ru: "PRO возможности", en: "PRO features", ro: "Funcții PRO" },
  "pro.subtitle": {
    ru: "Брендирование PDF, share-link, лиды и гибкие коэффициенты.",
    en: "Branded PDF, share links, leads, flexible coefficients.",
    ro: "PDF branduit, link share, lead-uri, coeficienți flexibili.",
  },
  "partners.title": { ru: "Партнёрам", en: "Partners", ro: "Parteneri" },
  "partners.subtitle": {
    ru: "Подключайтесь как подрядчик или поставщик материалов.",
    en: "Join as a contractor or material supplier.",
    ro: "Alătură-te ca antreprenor sau furnizor.",
  },
  "wizard.title": { ru: "Мастер расчёта", en: "Estimate wizard", ro: "Wizard estimare" },
  "wizard.step.object": { ru: "Объект", en: "Object", ro: "Obiect" },
  "wizard.step.systems": { ru: "Системы", en: "Systems", ro: "Sisteme" },
  "wizard.step.review": { ru: "Проверка", en: "Review", ro: "Verificare" },
  "wizard.step.generate": { ru: "Смета", en: "Estimate", ro: "Deviz" },
  "object.country": { ru: "Страна", en: "Country", ro: "Țară" },
  "object.city": { ru: "Город", en: "City", ro: "Oraș" },
  "object.region": { ru: "Регион", en: "Region", ro: "Regiune" },
  "object.type": { ru: "Тип объекта", en: "Property type", ro: "Tip obiect" },
  "object.area": { ru: "Площадь, м²", en: "Area, m²", ro: "Suprafață, m²" },
  "object.rooms": { ru: "Комнаты", en: "Rooms", ro: "Camere" },
  "object.height": { ru: "Высота потолка", en: "Ceiling height", ro: "Înălțime tavan" },
  "object.urgency": { ru: "Срочность", en: "Urgency", ro: "Urgent" },
  "object.brand": { ru: "Бренды", en: "Brand preference", ro: "Preferință brand" },
  "type.apartment": { ru: "Квартира", en: "Apartment", ro: "Apartament" },
  "type.house": { ru: "Дом", en: "House", ro: "Casă" },
  "urgency.standard": { ru: "Обычные сроки", en: "Standard", ro: "Standard" },
  "urgency.urgent": { ru: "Срочно", en: "Urgent", ro: "Urgent" },
  "brand.budget": { ru: "Budget", en: "Budget", ro: "Buget" },
  "brand.mid": { ru: "Mid", en: "Mid", ro: "Mediu" },
  "brand.premium": { ru: "Premium", en: "Premium", ro: "Premium" },
  "brand.any": { ru: "Не важно", en: "Any", ro: "Nu contează" },
  "system.floorHeating": { ru: "Тёплый пол", en: "Floor heating", ro: "Încălzire în pardoseală" },
  "system.radiators": { ru: "Радиаторы", en: "Radiators", ro: "Radiatoare" },
  "system.boiler": { ru: "Котёл и обвязка", en: "Boiler", ro: "Cazan" },
  "system.electrical": { ru: "Электрика", en: "Electrical", ro: "Electric" },
  "system.plumbing": { ru: "Сантехника", en: "Plumbing", ro: "Sanitar" },
  "system.area": { ru: "Площадь", en: "Area", ro: "Suprafață" },
  "system.layout": { ru: "Укладка", en: "Layout", ro: "Montaj" },
  "system.simple": { ru: "Простая", en: "Simple", ro: "Simplu" },
  "system.complex": { ru: "Сложная", en: "Complex", ro: "Complex" },
  "system.collector": { ru: "Коллектор", en: "Collector", ro: "Colector" },
  "system.automation": { ru: "Автоматика", en: "Automation", ro: "Automatizare" },
  "system.count": { ru: "Количество", en: "Count", ro: "Număr" },
  "system.roomsBased": { ru: "По комнатам", en: "By rooms", ro: "Pe camere" },
  "system.scheme": { ru: "Схема", en: "Scheme", ro: "Schema" },
  "system.singlePipe": { ru: "Однотрубная", en: "Single-pipe", ro: "Monotub" },
  "system.twoPipe": { ru: "Двухтрубная", en: "Two-pipe", ro: "Dublu-tub" },
  "system.thermoHeads": { ru: "Термоголовки", en: "Thermo heads", ro: "Capete termostat" },
  "system.boilerType": { ru: "Тип котла", en: "Boiler type", ro: "Tip cazan" },
  "system.boiler.gas": { ru: "Газовый", en: "Gas", ro: "Gaz" },
  "system.boiler.solid": { ru: "Твердотопливный", en: "Solid fuel", ro: "Solid" },
  "system.boiler.electric": { ru: "Электро", en: "Electric", ro: "Electric" },
  "system.pump": { ru: "Насос", en: "Pump", ro: "Pompă" },
  "system.expansionTank": { ru: "Расширительный бак", en: "Expansion tank", ro: "Vas expansiune" },
  "system.filters": { ru: "Фильтры", en: "Filters", ro: "Filtre" },
  "system.sockets": { ru: "Розетки", en: "Sockets", ro: "Prize" },
  "system.switches": { ru: "Выключатели", en: "Switches", ro: "Întrerupătoare" },
  "system.lights": { ru: "Свет", en: "Lights", ro: "Iluminat" },
  "system.panel": { ru: "Щит", en: "Panel", ro: "Tablou" },
  "system.waterPoints": { ru: "Точки воды", en: "Water points", ro: "Puncte apă" },
  "system.sewerPoints": { ru: "Точки канализации", en: "Sewer points", ro: "Puncte canalizare" },
  "review.title": { ru: "Проверка параметров", en: "Review inputs", ro: "Verificare date" },
  "result.title": { ru: "Готовая смета", en: "Estimate result", ro: "Rezultatul devizului" },
  "result.packages": { ru: "Пакеты", en: "Packages", ro: "Pachete" },
  "result.package.economy": { ru: "Economy", en: "Economy", ro: "Economy" },
  "result.package.standard": { ru: "Standard", en: "Standard", ro: "Standard" },
  "result.package.pro": { ru: "Pro", en: "Pro", ro: "Pro" },
  "result.works": { ru: "Детальная смета работ", en: "Detailed works", ro: "Lucrări detaliate" },
  "result.materials": { ru: "Материалы и аналоги", en: "Materials & analogs", ro: "Materiale & analogi" },
  "result.stages": { ru: "Этапы работ", en: "Stages", ro: "Etape" },
  "result.checklist": { ru: "Чек-лист ошибок", en: "Error checklist", ro: "Checklist erori" },
  "result.how": { ru: "Как считали", en: "How we calculated", ro: "Cum am calculat" },
  "result.diagrams": { ru: "Схемы", en: "Diagrams", ro: "Scheme" },
  "result.lead.title": { ru: "Получить консультацию", en: "Request consultation", ro: "Solicită consultanță" },
  "result.lead.name": { ru: "Имя", en: "Name", ro: "Nume" },
  "result.lead.contact": { ru: "Телефон или email", en: "Phone or email", ro: "Telefon sau email" },
  "result.lead.city": { ru: "Город", en: "City", ro: "Oraș" },
  "result.lead.comment": { ru: "Комментарий", en: "Comment", ro: "Comentariu" },
  "dashboard.title": { ru: "Кабинет", en: "Dashboard", ro: "Panou" },
  "dashboard.estimates": { ru: "Мои сметы", en: "My estimates", ro: "Devizele mele" },
  "dashboard.leads": { ru: "Мои лиды", en: "My leads", ro: "Lead-urile mele" },
  "dashboard.profile": { ru: "Профиль", en: "Profile", ro: "Profil" },
  "dashboard.noEstimates": { ru: "Смет пока нет.", en: "No estimates yet.", ro: "Nu există devize." },
  "dashboard.noLeads": { ru: "Лидов пока нет.", en: "No leads yet.", ro: "Nu există lead-uri." },
  "pro.plan.title": { ru: "Планы PRO", en: "PRO plans", ro: "Planuri PRO" },
  "pro.settings": { ru: "Настройки PRO", en: "PRO settings", ro: "Setări PRO" },
  "admin.title": { ru: "Админ-панель", en: "Admin panel", ro: "Admin" },
  "admin.catalogs": { ru: "Каталоги", en: "Catalogs", ro: "Cataloage" },
  "admin.regions": { ru: "Коэффициенты регионов", en: "Region coefficients", ro: "Coeficienți regiuni" },
  "admin.fx": { ru: "Курсы валют", en: "FX rates", ro: "Curs valutar" },
  "admin.presets": { ru: "Пресеты", en: "Presets", ro: "Preseturi" },
  "admin.leads": { ru: "Лиды и сметы", en: "Leads & estimates", ro: "Lead-uri & devize" },
  "admin.diagrams": { ru: "Схемы", en: "Diagrams", ro: "Scheme" },
  "admin.diagrams.templates": { ru: "Шаблоны", en: "Templates", ro: "Șabloane" },
  "admin.diagrams.rules": { ru: "Правила", en: "Rules", ro: "Reguli" },
  "admin.diagrams.editor": { ru: "Конструктор", en: "Editor", ro: "Editor" },
  "admin.rules.priority": { ru: "Приоритет", en: "Priority", ro: "Prioritate" },
  "admin.rules.condition": { ru: "Условия", en: "Conditions", ro: "Condiții" },
  "admin.rules.action": { ru: "Действия", en: "Actions", ro: "Acțiuni" },
  "admin.rules.template": { ru: "шаблон", en: "template", ro: "șablon" },
  "status.draft": { ru: "Черновик", en: "Draft", ro: "Schiță" },
  "status.completed": { ru: "Готово", en: "Completed", ro: "Finalizat" },
  "pdf.watermark": { ru: "DEMO", en: "DEMO", ro: "DEMO" },
  "landing.packages.title": { ru: "3 пакета", en: "3 packages", ro: "3 pachete" },
  "landing.packages.desc": {
    ru: "Economy / Standard / Pro с диапазонами и сроками.",
    en: "Economy / Standard / Pro with ranges and timelines.",
    ro: "Economy / Standard / Pro cu intervale și termene.",
  },
  "landing.method.title": { ru: "Понятная методика", en: "Clear methodology", ro: "Metodologie clară" },
  "landing.method.desc": {
    ru: "Коэффициенты, прозрачные расчёты и сохранённые формулы.",
    en: "Coefficients, transparent calculations, saved formulas.",
    ro: "Coeficienți, calcule transparente și formule salvate.",
  },
  "landing.pdf.title": { ru: "PDF с диаграммами", en: "PDF with diagrams", ro: "PDF cu scheme" },
  "landing.pdf.desc": {
    ru: "Экспорт отчёта со схемами из шаблонов.",
    en: "Export report with template-based diagrams.",
    ro: "Exportă raport cu scheme din șabloane.",
  },
  "pro.feature1": { ru: "PDF без DEMO watermark + брендинг", en: "PDF without DEMO + branding", ro: "PDF fără DEMO + branding" },
  "pro.feature2": { ru: "Share-link и экспорт лидов CSV", en: "Share link and CSV leads export", ro: "Link share și export CSV lead-uri" },
  "pro.feature3": { ru: "Настройка коэффициентов и маржи", en: "Adjust coefficients and margin", ro: "Ajustează coeficienți și marjă" },
  "partners.item1": { ru: "Интеграция каталога материалов и логистики.", en: "Materials catalog & logistics integration.", ro: "Integrare catalog materiale și logistică." },
  "partners.item2": { ru: "Подрядчики получают лиды с привязкой к региону.", en: "Contractors receive region-based leads.", ro: "Contractorii primesc lead-uri pe regiune." },
  "partners.item3": { ru: "White-label отчёты и персональные условия.", en: "White-label reports and custom terms.", ro: "Rapoarte white-label și condiții personalizate." },
  "partners.item4": { ru: "Совместная аналитика и планирование поставок.", en: "Shared analytics and supply planning.", ro: "Analize comune și planificare livrări." },
  "calc.object.desc": {
    ru: "Заполните параметры объекта, чтобы применить региональные коэффициенты.",
    en: "Fill in object details to apply regional coefficients.",
    ro: "Completează detaliile pentru coeficienți regionali.",
  },
  "calc.systems.desc": {
    ru: "Включите нужные системы и заполните ключевые параметры.",
    en: "Enable systems and fill key parameters.",
    ro: "Activează sisteme și completează parametri.",
  },
  "calc.review.desc": {
    ru: "Проверьте сводку данных. Черновик автосохранён.",
    en: "Review the summary. Draft autosaved.",
    ro: "Verifică sumarul. Ciornă salvată automat.",
  },
  "calc.review.object": { ru: "Объект", en: "Object", ro: "Obiect" },
  "calc.review.systems": { ru: "Системы", en: "Systems", ro: "Sisteme" },
  "calc.review.area": { ru: "Площадь", en: "Area", ro: "Suprafață" },
  "calc.review.rooms": { ru: "Комнаты", en: "Rooms", ro: "Camere" },
  "calc.review.height": { ru: "Высота", en: "Height", ro: "Înălțime" },
  "calc.review.urgency": { ru: "Срочность", en: "Urgency", ro: "Urgent" },
  "calc.systems.enabled": { ru: "включено", en: "enabled", ro: "activ" },
  "calc.systems.disabled": { ru: "выключено", en: "disabled", ro: "inactiv" },
  "calc.generate.desc": {
    ru: "Нажмите кнопку ниже, чтобы сформировать смету и перейти к результату.",
    en: "Click below to generate the estimate and view the result.",
    ro: "Apasă pentru a genera devizul și a vedea rezultatul.",
  },
  "calc.generate.summary": {
    ru: "Будет создана смета и PDF-отчёт для выбранного объекта.",
    en: "An estimate and PDF report will be created for the selected object.",
    ro: "Se va crea deviz și PDF pentru obiectul ales.",
  },
  "result.table.package": { ru: "Пакет", en: "Package", ro: "Pachet" },
  "result.table.labor": { ru: "Работы", en: "Labor", ro: "Lucrări" },
  "result.table.materials": { ru: "Материалы", en: "Materials", ro: "Materiale" },
  "result.table.total": { ru: "Итого", en: "Total", ro: "Total" },
  "result.table.range": { ru: "Диапазон", en: "Range", ro: "Interval" },
  "result.table.duration": { ru: "Сроки", en: "Duration", ro: "Durată" },
  "result.table.days": { ru: "дней", en: "days", ro: "zile" },
  "result.materials.analogs": { ru: "Аналоги", en: "Analogs", ro: "Analog" },
  "result.lead.spam": { ru: "Спам заблокирован.", en: "Spam blocked.", ro: "Spam blocat." },
  "result.lead.rate": { ru: "Слишком много запросов. Попробуйте позже.", en: "Too many requests. Try later.", ro: "Prea multe cereri. Încearcă mai târziu." },
  "result.lead.success": { ru: "Спасибо! Мы свяжемся с вами.", en: "Thanks! We'll contact you.", ro: "Mulțumim! Te contactăm." },
  "result.summary.rooms": { ru: "комнат", en: "rooms", ro: "camere" },
  "profile.name": { ru: "Имя", en: "Name", ro: "Nume" },
  "profile.city": { ru: "Город", en: "City", ro: "Oraș" },
  "pro.plan.starter": { ru: "Starter", en: "Starter", ro: "Starter" },
  "pro.plan.growth": { ru: "Growth", en: "Growth", ro: "Growth" },
  "pro.plan.enterprise": { ru: "Enterprise", en: "Enterprise", ro: "Enterprise" },
  "pro.plan.price1": { ru: "€39 / мес", en: "€39 / mo", ro: "€39 / lună" },
  "pro.plan.price2": { ru: "€79 / мес", en: "€79 / mo", ro: "€79 / lună" },
  "pro.plan.price3": { ru: "€149 / мес", en: "€149 / mo", ro: "€149 / lună" },
  "pro.plan.feature1": { ru: "PDF без DEMO", en: "PDF without DEMO", ro: "PDF fără DEMO" },
  "pro.plan.feature2": { ru: "Брендинг", en: "Branding", ro: "Branding" },
  "pro.plan.feature3": { ru: "Share-link", en: "Share link", ro: "Link share" },
  "pro.plan.feature4": { ru: "CSV лиды", en: "CSV leads", ro: "Lead-uri CSV" },
  "pro.plan.feature5": { ru: "Мульти-проекты", en: "Multi-projects", ro: "Multi-proiecte" },
  "pro.plan.feature6": { ru: "Поддержка", en: "Support", ro: "Suport" },
  "pro.plan.feature7": { ru: "Белая метка", en: "White-label", ro: "White-label" },
  "pro.plan.feature8": { ru: "SLA", en: "SLA", ro: "SLA" },
  "pro.plan.feature9": { ru: "API", en: "API", ro: "API" },
  "pro.plan.cta": { ru: "Подключить", en: "Upgrade", ro: "Activează" },
  "pro.settings.company": { ru: "Компания", en: "Company", ro: "Companie" },
  "pro.settings.phone": { ru: "Телефон", en: "Phone", ro: "Telefon" },
  "pro.settings.margin": { ru: "Маржа, %", en: "Margin, %", ro: "Marjă, %" },
  "pro.settings.discount": { ru: "Скидка, %", en: "Discount, %", ro: "Discount, %" },
  "admin.canvas.title": { ru: "Canvas", en: "Canvas", ro: "Canvas" },
  "admin.canvas.grid": { ru: "Grid 24px · Zoom", en: "Grid 24px · Zoom", ro: "Grid 24px · Zoom" },
  "admin.properties.title": { ru: "Properties", en: "Properties", ro: "Proprietăți" },
  "admin.properties.select": { ru: "Выберите элемент.", en: "Select an element.", ro: "Selectează un element." },
  "admin.ai.rate": { ru: "AI rate limit reached. Попробуйте позже.", en: "AI rate limit reached. Try later.", ro: "Limită AI atinsă. Încearcă mai târziu." },
  "admin.ai.cached": { ru: "AI cached response used.", en: "AI cached response used.", ro: "Răspuns AI din cache." },
  "admin.ai.executed": { ru: "AI action executed.", en: "AI action executed.", ro: "Acțiune AI executată." },
  "admin.templates.json": { ru: "Template JSON", en: "Template JSON", ro: "Template JSON" },
  "admin.prop.x": { ru: "X", en: "X", ro: "X" },
  "admin.prop.y": { ru: "Y", en: "Y", ro: "Y" },
  "admin.prop.w": { ru: "W", en: "W", ro: "W" },
  "admin.prop.h": { ru: "H", en: "H", ro: "H" },
  "admin.prop.text": { ru: "Текст", en: "Text", ro: "Text" },
  "admin.prop.stroke": { ru: "Обводка", en: "Stroke", ro: "Contur" },
  "admin.prop.fill": { ru: "Заливка", en: "Fill", ro: "Umplere" },
  "admin.newText": { ru: "Новый текст", en: "New text", ro: "Text nou" },
  "admin.ai.draftTitle": { ru: "Черновик шаблона", en: "Draft layout", ro: "Schiță șablon" },
  "admin.variantLayer": { ru: "Вариант", en: "Variant", ro: "Variantă" },
  "admin.preview.title": { ru: "Preview with estimate", en: "Preview with estimate", ro: "Previzualizare cu deviz" },
  "admin.preview.desc": { ru: "Выберите смету и проверьте, как применяются правила.", en: "Choose an estimate to see rules applied.", ro: "Alege deviz pentru a vedea reguli." },
  "admin.preview.auth": { ru: "Авторизован", en: "Signed in as", ro: "Autentificat ca" },
  "admin.catalog.materials": { ru: "Материалы", en: "Materials", ro: "Materiale" },
  "admin.stats.estimates": { ru: "Смет", en: "Estimates", ro: "Devize" },
  "admin.stats.leads": { ru: "Лидов", en: "Leads", ro: "Lead-uri" },
  "admin.rooms.label": { ru: "комнат", en: "rooms", ro: "camere" },
  "step.label": { ru: "ШАГ", en: "STEP", ro: "PAS" },
  "notfound.title": { ru: "Страница не найдена.", en: "Page not found.", ro: "Pagina nu a fost găsită." },
  "notfound.desc": { ru: "Вернитесь на главную или начните новый расчёт.", en: "Return home or start a new estimate.", ro: "Revino acasă sau începe un nou deviz." },
  "notfound.home": { ru: "На главную", en: "Home", ro: "Acasă" },
  "notfound.calc": { ru: "Рассчитать смету", en: "Calculate estimate", ro: "Calculează deviz" },
  "pdf.title": { ru: "RenovEstimate — отчёт", en: "RenovEstimate — report", ro: "RenovEstimate — raport" },
  "pdf.windowTitle": { ru: "RenovEstimate PDF", en: "RenovEstimate PDF", ro: "RenovEstimate PDF" },
  "pdf.city": { ru: "Город", en: "City", ro: "Oraș" },
  "pdf.packages": { ru: "Пакеты", en: "Packages", ro: "Pachete" },
  "pdf.works": { ru: "Детальные работы", en: "Detailed works", ro: "Lucrări detaliate" },
  "pdf.materials": { ru: "Материалы и аналоги", en: "Materials and analogs", ro: "Materiale și analogi" },
  "pdf.stages": { ru: "Этапы", en: "Stages", ro: "Etape" },
  "pdf.checklist": { ru: "Чек-лист", en: "Checklist", ro: "Checklist" },
  "pdf.calculated": { ru: "Как считали", en: "How we calculated", ro: "Cum am calculat" },
  "how.region": { ru: "Коэффициент региона", en: "Region coefficient", ro: "Coeficient regional" },
  "how.urgency": { ru: "Коэффициент срочности", en: "Urgency coefficient", ro: "Coeficient urgență" },
  "how.complexity": { ru: "Коэффициент сложности (высота/комнаты)", en: "Complexity coefficient (height/rooms)", ro: "Coeficient complexitate (înălțime/camere)" },
  "how.range": { ru: "Диапазон", en: "Range", ro: "Interval" },
  "quantity.floor.pipe": { ru: "Труба тёплого пола", en: "Floor heating pipe", ro: "Țeavă încălzire pardoseală" },
  "quantity.floor.pipe.reason": { ru: "Площадь · запас 12%", en: "Area · 12% reserve", ro: "Suprafață · rezervă 12%" },
  "quantity.floor.circuits": { ru: "Контуры", en: "Circuits", ro: "Circuite" },
  "quantity.floor.circuits.reason": { ru: "Площадь / 12 м² на контур", en: "Area / 12 m² per circuit", ro: "Suprafață / 12 m² per circuit" },
  "quantity.floor.pipePerCircuit": { ru: "Труба на контур", en: "Pipe per circuit", ro: "Țeavă per circuit" },
  "quantity.floor.pipePerCircuit.reason": { ru: "Порционно для удобства укладки", en: "Segmented for easy layout", ro: "Segmentat pentru montaj" },
  "quantity.electrical.linesSockets": { ru: "Линий розеток", en: "Socket lines", ro: "Linii prize" },
  "quantity.electrical.linesSockets.reason": { ru: "Каждые 10 розеток — отдельная линия", en: "Each 10 sockets — separate line", ro: "La 10 prize — linie separată" },
  "quantity.electrical.linesLights": { ru: "Линий света", en: "Lighting lines", ro: "Linii iluminat" },
  "quantity.electrical.linesLights.reason": { ru: "Каждые 12 светильников — отдельная линия", en: "Each 12 lights — separate line", ro: "La 12 corpuri — linie separată" },
  "quantity.electrical.cable": { ru: "Кабель", en: "Cable", ro: "Cablu" },
  "quantity.electrical.cable.reason": { ru: "Расчёт по точкам + запас 10%", en: "Points-based + 10% reserve", ro: "După puncte + rezervă 10%" },
  "quantity.plumbing.pipe": { ru: "Трубы воды", en: "Water pipes", ro: "Țevi apă" },
  "quantity.plumbing.pipe.reason": { ru: "6 м на точку + запас 10%", en: "6 m per point + 10% reserve", ro: "6 m/punct + rezervă 10%" },
  "quantity.plumbing.fittings": { ru: "Фитинги", en: "Fittings", ro: "Fitinguri" },
  "quantity.plumbing.fittings.reason": { ru: "4 фитинга на точку", en: "4 fittings per point", ro: "4 fitinguri per punct" },
  "quantity.radiators": { ru: "Радиаторы", en: "Radiators", ro: "Radiatoare" },
  "quantity.radiators.reason.manual": { ru: "Задано вручную", en: "Entered manually", ro: "Introdus manual" },
  "quantity.radiators.reason.rooms": { ru: "1.5 радиатора на комнату", en: "1.5 radiators per room", ro: "1.5 radiatoare pe cameră" },
  "quantity.boiler.kit": { ru: "Базовый комплект обвязки", en: "Boiler piping kit", ro: "Kit conexiuni cazan" },
  "quantity.boiler.kit.reason": { ru: "Монтаж котла и обвязки", en: "Boiler installation and piping", ro: "Montaj cazan și conexiuni" },
  "stage.1": { ru: "Подготовка проекта, проверка чертежей и замеры.", en: "Project prep, drawings check, measurements.", ro: "Pregătire proiect, verificare planuri, măsurători." },
  "stage.2": { ru: "Поставка материалов и комплектация склада.", en: "Materials delivery and staging.", ro: "Livrare materiale și pregătire." },
  "stage.3": { ru: "Монтаж инженерных систем и трасс.", en: "Install engineering systems and routes.", ro: "Montaj sisteme inginerești și trasee." },
  "stage.4": { ru: "Тестирование, опрессовка, настройка автоматики.", en: "Testing, pressure test, automation setup.", ro: "Testare, presiune, setare automatizări." },
  "stage.5": { ru: "Финальная проверка, передача отчёта и схем.", en: "Final inspection, report and diagrams delivery.", ro: "Verificare finală, raport și scheme." },
  "checklist.1": { ru: "Проверить соответствие мощности котла площади объекта.", en: "Verify boiler power matches area.", ro: "Verifică puterea cazanului vs suprafață." },
  "checklist.2": { ru: "Не превышать допустимую длину контуров тёплого пола.", en: "Do not exceed floor heating loop length.", ro: "Nu depăși lungimea buclelor." },
  "checklist.3": { ru: "Согласовать количество радиаторов с теплопотерями.", en: "Align radiator count with heat loss.", ro: "Ajustează radiatoarele la pierderi." },
  "checklist.4": { ru: "Не экономить на коллекторе и запорной арматуре.", en: "Avoid saving on collectors and valves.", ro: "Nu economisi la colector și valve." },
  "checklist.5": { ru: "Учитывать отдельные линии для кухни и санузлов.", en: "Separate lines for kitchen and bathrooms.", ro: "Linii separate pentru bucătărie și băi." },
  "checklist.6": { ru: "Сделать резервные кабели для будущих нагрузок.", en: "Provide reserve cables for future loads.", ro: "Cabluri de rezervă pentru sarcini viitoare." },
  "checklist.7": { ru: "Оставить доступ к фильтрам и расширительному баку.", en: "Ensure access to filters and expansion tank.", ro: "Asigură acces la filtre și vas." },
  "checklist.8": { ru: "Применять УЗО и автомат защиты в щите.", en: "Use RCD and breakers in the panel.", ro: "Folosește RCD și siguranțe." },
  "checklist.9": { ru: "Проверить гидроизоляцию в мокрых зонах.", en: "Check waterproofing in wet zones.", ro: "Verifică hidroizolația." },
  "checklist.10": { ru: "Не смешивать несовместимые материалы труб.", en: "Do not mix incompatible pipe materials.", ro: "Nu combina materiale incompatibile." },
  "checklist.11": { ru: "Закладывать запас на фитинги и крепёж.", en: "Add reserve for fittings and fasteners.", ro: "Adaugă rezervă pentru fitinguri și fixări." },
  "checklist.12": { ru: "Подписать все линии и точки подключения.", en: "Label all lines and connection points.", ro: "Etichetează toate liniile." },
  "diagram.electrical.panel": { ru: "Щит", en: "Panel", ro: "Tablou" },
  "diagram.electrical.summary": {
    ru: "Кабель: {cableTotal} м, линий: {linesSockets}+{linesLights}",
    en: "Cable: {cableTotal} m, lines: {linesSockets}+{linesLights}",
    ro: "Cablu: {cableTotal} m, linii: {linesSockets}+{linesLights}",
  },
  "diagram.radiators.count": { ru: "Радиаторов: {radiators}", en: "Radiators: {radiators}", ro: "Radiatoare: {radiators}" },
  "diagram.radiators.twoPipe": {
    ru: "Двухтрубная схема · радиаторов {radiators}",
    en: "Two-pipe scheme · radiators {radiators}",
    ro: "Schema două țevi · radiatoare {radiators}",
  },
  "diagram.boiler.type": { ru: "Тип котла: {boilerType}", en: "Boiler type: {boilerType}", ro: "Tip cazan: {boilerType}" },
  "diagram.floor.summary": {
    ru: "Контуров: {circuitsCount}, труба {pipeTotal} м",
    en: "Loops: {circuitsCount}, pipe {pipeTotal} m",
    ro: "Bucle: {circuitsCount}, țeavă {pipeTotal} m",
  },
  "diagram.plumbing.summary": {
    ru: "Вода: {waterPoints} · Канализация: {sewerPoints}",
    en: "Water: {waterPoints} · Sewer: {sewerPoints}",
    ro: "Apă: {waterPoints} · Canalizare: {sewerPoints}",
  },
  "diagram.template.electrical.base": { ru: "Электрика: базовая трасса", en: "Electrical: base route", ro: "Electric: traseu de bază" },
  "diagram.template.radiators.single": { ru: "Радиаторы: однотрубка", en: "Radiators: single pipe", ro: "Radiatoare: monotub" },
  "diagram.template.radiators.two": { ru: "Радиаторы: двухтрубка", en: "Radiators: two pipe", ro: "Radiatoare: două țevi" },
  "diagram.template.boiler.base": { ru: "Котёл и обвязка", en: "Boiler & piping", ro: "Cazan și conexiuni" },
  "diagram.template.floor.base": { ru: "Тёплый пол", en: "Floor heating", ro: "Încălzire în pardoseală" },
  "diagram.template.plumbing.base": { ru: "Сантехника", en: "Plumbing", ro: "Sanitar" },
  "unit.meter": { ru: "м", en: "m", ro: "m" },
  "unit.piece": { ru: "шт", en: "pcs", ro: "buc" },
  "unit.set": { ru: "комплект", en: "set", ro: "set" },
  "unit.squareMeter": { ru: "м²", en: "m²", ro: "m²" },
  "misc.na": { ru: "—", en: "—", ro: "—" },
  "price.floor.pipe": { ru: "Труба тёплого пола", en: "Floor heating pipe", ro: "Țeavă încălzire pardoseală" },
  "price.floor.collector": { ru: "Коллекторный узел", en: "Manifold unit", ro: "Unitate colector" },
  "price.radiators.unit": { ru: "Радиатор", en: "Radiator", ro: "Radiator" },
  "price.boiler.install": { ru: "Монтаж котла и обвязки", en: "Boiler installation", ro: "Montaj cazan" },
  "price.electrical.cable": { ru: "Кабель силовой", en: "Power cable", ro: "Cablu electric" },
  "price.electrical.point": { ru: "Точка подключения", en: "Connection point", ro: "Punct conexiune" },
  "price.plumbing.pipe": { ru: "Трубы и фитинги", en: "Pipes and fittings", ro: "Țevi și fitinguri" },
  "price.plumbing.point": { ru: "Точка воды/канализации", en: "Water/sewer point", ro: "Punct apă/canalizare" },
  "material.floor.pipe": { ru: "PEX труба 16 мм", en: "PEX pipe 16 mm", ro: "Țeavă PEX 16 mm" },
  "material.floor.pipe.analog1": { ru: "PE-RT 16 мм", en: "PE-RT 16 mm", ro: "PE-RT 16 mm" },
  "material.floor.pipe.analog2": { ru: "PEX 17 мм", en: "PEX 17 mm", ro: "PEX 17 mm" },
  "material.radiators.aluminum": { ru: "Радиатор алюминиевый", en: "Aluminum radiator", ro: "Radiator aluminiu" },
  "material.radiators.analog1": { ru: "Стальной панельный", en: "Steel panel radiator", ro: "Radiator panou oțel" },
  "material.radiators.analog2": { ru: "Биметалл", en: "Bimetal radiator", ro: "Radiator bimetal" },
  "material.boiler.wall": { ru: "Котёл настенный", en: "Wall-mounted boiler", ro: "Cazan mural" },
  "material.boiler.analog1": { ru: "Котёл напольный", en: "Floor boiler", ro: "Cazan pe pardoseală" },
  "material.boiler.analog2": { ru: "Конденсационный котёл", en: "Condensing boiler", ro: "Cazan în condensație" },
  "material.electrical.cable": { ru: "Кабель ВВГнг", en: "VVGng cable", ro: "Cablu VVGng" },
  "material.electrical.analog1": { ru: "NYY", en: "NYY", ro: "NYY" },
  "material.electrical.analog2": { ru: "NYM", en: "NYM", ro: "NYM" },
  "material.plumbing.pipe": { ru: "Труба PPR", en: "PPR pipe", ro: "Țeavă PPR" },
  "material.plumbing.analog1": { ru: "PEX-AL-PEX", en: "PEX-AL-PEX", ro: "PEX-AL-PEX" },
  "material.plumbing.analog2": { ru: "Медь", en: "Copper", ro: "Cupru" },
  "preset.preset-1.name": { ru: "Квартира 60 м², 2 комнаты", en: "Apartment 60 m², 2 rooms", ro: "Apartament 60 m², 2 camere" },
  "preset.preset-1.desc": { ru: "Базовый проект с полным набором инженерии.", en: "Base project with full engineering set.", ro: "Proiect de bază cu set complet." },
  "preset.preset-2.name": { ru: "Дом 120 м², 5 комнат", en: "House 120 m², 5 rooms", ro: "Casă 120 m², 5 camere" },
  "preset.preset-2.desc": { ru: "Сложная укладка и высокий коэффициент региона.", en: "Complex layout and higher regional coefficient.", ro: "Montaj complex și coeficient regional ridicat." },
  "preset.preset-3.name": { ru: "Квартира 45 м², 1 комната", en: "Apartment 45 m², 1 room", ro: "Apartament 45 m², 1 cameră" },
  "preset.preset-3.desc": { ru: "Минимальный набор систем для экономичного пакета.", en: "Minimal systems for economy package.", ro: "Set minim de sisteme pentru economy." },
  "preset.preset-4.name": { ru: "Дом 90 м², 4 комнаты", en: "House 90 m², 4 rooms", ro: "Casă 90 m², 4 camere" },
  "preset.preset-4.desc": { ru: "Стандартный проект без тёплого пола.", en: "Standard project without floor heating.", ro: "Proiect standard fără încălzire în pardoseală." },
  "preset.preset-5.name": { ru: "Квартира 80 м², 3 комнаты", en: "Apartment 80 m², 3 rooms", ro: "Apartament 80 m², 3 camere" },
  "preset.preset-5.desc": { ru: "Баланс материалов и сроков.", en: "Balanced materials and timelines.", ro: "Echilibru materiale și termene." },
  "preset.preset-6.name": { ru: "Дом 150 м², 6 комнат", en: "House 150 m², 6 rooms", ro: "Casă 150 m², 6 camere" },
  "preset.preset-6.desc": { ru: "Максимальный набор систем и высокая нагрузка.", en: "Maximum systems and higher load.", ro: "Set maxim de sisteme și sarcină mare." },
  "preset.preset-7.name": { ru: "Апартаменты 55 м², 2 комнаты", en: "Apartment 55 m², 2 rooms", ro: "Apartament 55 m², 2 camere" },
  "preset.preset-7.desc": { ru: "Компактный проект с тёплым полом.", en: "Compact project with floor heating.", ro: "Proiect compact cu încălzire în pardoseală." },
  "preset.preset-8.name": { ru: "Дом 110 м², 4 комнаты", en: "House 110 m², 4 rooms", ro: "Casă 110 m², 4 camere" },
  "preset.preset-8.desc": { ru: "Двухтрубная схема с термоголовками.", en: "Two-pipe scheme with thermo heads.", ro: "Schemă cu două țevi și capete termostat." },
  "preset.preset-9.name": { ru: "Квартира 70 м², 3 комнаты", en: "Apartment 70 m², 3 rooms", ro: "Apartament 70 m², 3 camere" },
  "preset.preset-9.desc": { ru: "Стандартный проект с двухтрубной схемой.", en: "Standard project with two-pipe scheme.", ro: "Proiect standard cu schemă două țevi." },
  "preset.preset-10.name": { ru: "Дом 130 м², 5 комнат", en: "House 130 m², 5 rooms", ro: "Casă 130 m², 5 camere" },
  "preset.preset-10.desc": { ru: "Срочный проект с сложной укладкой.", en: "Urgent project with complex layout.", ro: "Proiect urgent cu montaj complex." },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<React.PropsWithChildren> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("language");
    if (stored === "ru" || stored === "en" || stored === "ro") {
      return stored;
    }
    return "ru";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  }, []);

  const t = useCallback(
    (key: string) => translations[key]?.[language] ?? translations[key]?.ru ?? key,
    [language]
  );

  const value = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
